// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fivetran

import (
	"context"
	"reflect"

	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source returns all available source types within your Fivetran account. This data source makes it easier to display Fivetran connectors within your application because it provides metadata including the proper source name (‘Facebook Ad Account’ instead of facebook_ad_account), the source icon, and links to Fivetran resources. As we update source names and icons, that metadata will automatically update within this endpoint.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := fivetran.GetConnectorsMetadata(ctx, &fivetran.GetConnectorsMetadataArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetConnectorsMetadata(ctx *pulumi.Context, args *GetConnectorsMetadataArgs, opts ...pulumi.InvokeOption) (*GetConnectorsMetadataResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetConnectorsMetadataResult
	err := ctx.Invoke("fivetran:index/getConnectorsMetadata:getConnectorsMetadata", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getConnectorsMetadata.
type GetConnectorsMetadataArgs struct {
	Sources []GetConnectorsMetadataSource `pulumi:"sources"`
}

// A collection of values returned by getConnectorsMetadata.
type GetConnectorsMetadataResult struct {
	// The ID of this resource.
	Id      string                        `pulumi:"id"`
	Sources []GetConnectorsMetadataSource `pulumi:"sources"`
}

func GetConnectorsMetadataOutput(ctx *pulumi.Context, args GetConnectorsMetadataOutputArgs, opts ...pulumi.InvokeOption) GetConnectorsMetadataResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetConnectorsMetadataResultOutput, error) {
			args := v.(GetConnectorsMetadataArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("fivetran:index/getConnectorsMetadata:getConnectorsMetadata", args, GetConnectorsMetadataResultOutput{}, options).(GetConnectorsMetadataResultOutput), nil
		}).(GetConnectorsMetadataResultOutput)
}

// A collection of arguments for invoking getConnectorsMetadata.
type GetConnectorsMetadataOutputArgs struct {
	Sources GetConnectorsMetadataSourceArrayInput `pulumi:"sources"`
}

func (GetConnectorsMetadataOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConnectorsMetadataArgs)(nil)).Elem()
}

// A collection of values returned by getConnectorsMetadata.
type GetConnectorsMetadataResultOutput struct{ *pulumi.OutputState }

func (GetConnectorsMetadataResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConnectorsMetadataResult)(nil)).Elem()
}

func (o GetConnectorsMetadataResultOutput) ToGetConnectorsMetadataResultOutput() GetConnectorsMetadataResultOutput {
	return o
}

func (o GetConnectorsMetadataResultOutput) ToGetConnectorsMetadataResultOutputWithContext(ctx context.Context) GetConnectorsMetadataResultOutput {
	return o
}

// The ID of this resource.
func (o GetConnectorsMetadataResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetConnectorsMetadataResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetConnectorsMetadataResultOutput) Sources() GetConnectorsMetadataSourceArrayOutput {
	return o.ApplyT(func(v GetConnectorsMetadataResult) []GetConnectorsMetadataSource { return v.Sources }).(GetConnectorsMetadataSourceArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConnectorsMetadataResultOutput{})
}
