// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fivetran

import (
	"context"
	"reflect"

	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source returns a destination object.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := fivetran.LookupDestination(ctx, &fivetran.LookupDestinationArgs{
//				Id: "anonymous_mystery",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupDestination(ctx *pulumi.Context, args *LookupDestinationArgs, opts ...pulumi.InvokeOption) (*LookupDestinationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDestinationResult
	err := ctx.Invoke("fivetran:index/getDestination:getDestination", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDestination.
type LookupDestinationArgs struct {
	Config *GetDestinationConfig `pulumi:"config"`
	Id     string                `pulumi:"id"`
}

// A collection of values returned by getDestination.
type LookupDestinationResult struct {
	Config                    *GetDestinationConfig `pulumi:"config"`
	DaylightSavingTimeEnabled bool                  `pulumi:"daylightSavingTimeEnabled"`
	GroupId                   string                `pulumi:"groupId"`
	Id                        string                `pulumi:"id"`
	Region                    string                `pulumi:"region"`
	Service                   string                `pulumi:"service"`
	SetupStatus               string                `pulumi:"setupStatus"`
	TimeZoneOffset            string                `pulumi:"timeZoneOffset"`
}

func LookupDestinationOutput(ctx *pulumi.Context, args LookupDestinationOutputArgs, opts ...pulumi.InvokeOption) LookupDestinationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDestinationResult, error) {
			args := v.(LookupDestinationArgs)
			r, err := LookupDestination(ctx, &args, opts...)
			var s LookupDestinationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDestinationResultOutput)
}

// A collection of arguments for invoking getDestination.
type LookupDestinationOutputArgs struct {
	Config GetDestinationConfigPtrInput `pulumi:"config"`
	Id     pulumi.StringInput           `pulumi:"id"`
}

func (LookupDestinationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDestinationArgs)(nil)).Elem()
}

// A collection of values returned by getDestination.
type LookupDestinationResultOutput struct{ *pulumi.OutputState }

func (LookupDestinationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDestinationResult)(nil)).Elem()
}

func (o LookupDestinationResultOutput) ToLookupDestinationResultOutput() LookupDestinationResultOutput {
	return o
}

func (o LookupDestinationResultOutput) ToLookupDestinationResultOutputWithContext(ctx context.Context) LookupDestinationResultOutput {
	return o
}

func (o LookupDestinationResultOutput) Config() GetDestinationConfigPtrOutput {
	return o.ApplyT(func(v LookupDestinationResult) *GetDestinationConfig { return v.Config }).(GetDestinationConfigPtrOutput)
}

func (o LookupDestinationResultOutput) DaylightSavingTimeEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDestinationResult) bool { return v.DaylightSavingTimeEnabled }).(pulumi.BoolOutput)
}

func (o LookupDestinationResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationResult) string { return v.GroupId }).(pulumi.StringOutput)
}

func (o LookupDestinationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDestinationResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupDestinationResultOutput) Service() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationResult) string { return v.Service }).(pulumi.StringOutput)
}

func (o LookupDestinationResultOutput) SetupStatus() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationResult) string { return v.SetupStatus }).(pulumi.StringOutput)
}

func (o LookupDestinationResultOutput) TimeZoneOffset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationResult) string { return v.TimeZoneOffset }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDestinationResultOutput{})
}
