// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fivetran

import (
	"context"
	"reflect"

	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source returns a list of all proxy agents within your Fivetran account.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := fivetran.GetProxyAgents(ctx, &fivetran.GetProxyAgentsArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetProxyAgents(ctx *pulumi.Context, args *GetProxyAgentsArgs, opts ...pulumi.InvokeOption) (*GetProxyAgentsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProxyAgentsResult
	err := ctx.Invoke("fivetran:index/getProxyAgents:getProxyAgents", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProxyAgents.
type GetProxyAgentsArgs struct {
	Items []GetProxyAgentsItem `pulumi:"items"`
}

// A collection of values returned by getProxyAgents.
type GetProxyAgentsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id    string               `pulumi:"id"`
	Items []GetProxyAgentsItem `pulumi:"items"`
}

func GetProxyAgentsOutput(ctx *pulumi.Context, args GetProxyAgentsOutputArgs, opts ...pulumi.InvokeOption) GetProxyAgentsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetProxyAgentsResultOutput, error) {
			args := v.(GetProxyAgentsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("fivetran:index/getProxyAgents:getProxyAgents", args, GetProxyAgentsResultOutput{}, options).(GetProxyAgentsResultOutput), nil
		}).(GetProxyAgentsResultOutput)
}

// A collection of arguments for invoking getProxyAgents.
type GetProxyAgentsOutputArgs struct {
	Items GetProxyAgentsItemArrayInput `pulumi:"items"`
}

func (GetProxyAgentsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProxyAgentsArgs)(nil)).Elem()
}

// A collection of values returned by getProxyAgents.
type GetProxyAgentsResultOutput struct{ *pulumi.OutputState }

func (GetProxyAgentsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProxyAgentsResult)(nil)).Elem()
}

func (o GetProxyAgentsResultOutput) ToGetProxyAgentsResultOutput() GetProxyAgentsResultOutput {
	return o
}

func (o GetProxyAgentsResultOutput) ToGetProxyAgentsResultOutputWithContext(ctx context.Context) GetProxyAgentsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetProxyAgentsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProxyAgentsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetProxyAgentsResultOutput) Items() GetProxyAgentsItemArrayOutput {
	return o.ApplyT(func(v GetProxyAgentsResult) []GetProxyAgentsItem { return v.Items }).(GetProxyAgentsItemArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProxyAgentsResultOutput{})
}
