// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fivetran

import (
	"context"
	"reflect"

	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPrivateLinks(ctx *pulumi.Context, args *GetPrivateLinksArgs, opts ...pulumi.InvokeOption) (*GetPrivateLinksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPrivateLinksResult
	err := ctx.Invoke("fivetran:index/getPrivateLinks:getPrivateLinks", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPrivateLinks.
type GetPrivateLinksArgs struct {
	Items []GetPrivateLinksItem `pulumi:"items"`
}

// A collection of values returned by getPrivateLinks.
type GetPrivateLinksResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id    string                `pulumi:"id"`
	Items []GetPrivateLinksItem `pulumi:"items"`
}

func GetPrivateLinksOutput(ctx *pulumi.Context, args GetPrivateLinksOutputArgs, opts ...pulumi.InvokeOption) GetPrivateLinksResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPrivateLinksResultOutput, error) {
			args := v.(GetPrivateLinksArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("fivetran:index/getPrivateLinks:getPrivateLinks", args, GetPrivateLinksResultOutput{}, options).(GetPrivateLinksResultOutput), nil
		}).(GetPrivateLinksResultOutput)
}

// A collection of arguments for invoking getPrivateLinks.
type GetPrivateLinksOutputArgs struct {
	Items GetPrivateLinksItemArrayInput `pulumi:"items"`
}

func (GetPrivateLinksOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinksArgs)(nil)).Elem()
}

// A collection of values returned by getPrivateLinks.
type GetPrivateLinksResultOutput struct{ *pulumi.OutputState }

func (GetPrivateLinksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinksResult)(nil)).Elem()
}

func (o GetPrivateLinksResultOutput) ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput {
	return o
}

func (o GetPrivateLinksResultOutput) ToGetPrivateLinksResultOutputWithContext(ctx context.Context) GetPrivateLinksResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetPrivateLinksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPrivateLinksResultOutput) Items() GetPrivateLinksItemArrayOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) []GetPrivateLinksItem { return v.Items }).(GetPrivateLinksItemArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPrivateLinksResultOutput{})
}
