// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fivetran

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/footholdtech/pulumi-fivetran/sdk/go/fivetran/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "fivetran:index/connector:Connector":
		r = &Connector{}
	case "fivetran:index/connectorSchedule:ConnectorSchedule":
		r = &ConnectorSchedule{}
	case "fivetran:index/connectorSchemaConfig:ConnectorSchemaConfig":
		r = &ConnectorSchemaConfig{}
	case "fivetran:index/dbtProject:DbtProject":
		r = &DbtProject{}
	case "fivetran:index/dbtTransformation:DbtTransformation":
		r = &DbtTransformation{}
	case "fivetran:index/destination:Destination":
		r = &Destination{}
	case "fivetran:index/group:Group":
		r = &Group{}
	case "fivetran:index/groupUsers:GroupUsers":
		r = &GroupUsers{}
	case "fivetran:index/user:User":
		r = &User{}
	case "fivetran:index/webhook:Webhook":
		r = &Webhook{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:fivetran" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/connector",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/connectorSchedule",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/connectorSchemaConfig",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/dbtProject",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/dbtTransformation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/destination",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/groupUsers",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fivetran",
		"index/webhook",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"fivetran",
		&pkg{version},
	)
}
