// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran
{
    public static class GetConnectors
    {
        /// <summary>
        /// This data source returns list of connector objects.
        /// </summary>
        public static Task<GetConnectorsResult> InvokeAsync(GetConnectorsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetConnectorsResult>("fivetran:index/getConnectors:getConnectors", args ?? new GetConnectorsArgs(), options.WithDefaults());

        /// <summary>
        /// This data source returns list of connector objects.
        /// </summary>
        public static Output<GetConnectorsResult> Invoke(GetConnectorsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetConnectorsResult>("fivetran:index/getConnectors:getConnectors", args ?? new GetConnectorsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// This data source returns list of connector objects.
        /// </summary>
        public static Output<GetConnectorsResult> Invoke(GetConnectorsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetConnectorsResult>("fivetran:index/getConnectors:getConnectors", args ?? new GetConnectorsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetConnectorsArgs : global::Pulumi.InvokeArgs
    {
        [Input("connectors")]
        private List<Inputs.GetConnectorsConnectorArgs>? _connectors;
        public List<Inputs.GetConnectorsConnectorArgs> Connectors
        {
            get => _connectors ?? (_connectors = new List<Inputs.GetConnectorsConnectorArgs>());
            set => _connectors = value;
        }

        public GetConnectorsArgs()
        {
        }
        public static new GetConnectorsArgs Empty => new GetConnectorsArgs();
    }

    public sealed class GetConnectorsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("connectors")]
        private InputList<Inputs.GetConnectorsConnectorInputArgs>? _connectors;
        public InputList<Inputs.GetConnectorsConnectorInputArgs> Connectors
        {
            get => _connectors ?? (_connectors = new InputList<Inputs.GetConnectorsConnectorInputArgs>());
            set => _connectors = value;
        }

        public GetConnectorsInvokeArgs()
        {
        }
        public static new GetConnectorsInvokeArgs Empty => new GetConnectorsInvokeArgs();
    }


    [OutputType]
    public sealed class GetConnectorsResult
    {
        public readonly ImmutableArray<Outputs.GetConnectorsConnectorResult> Connectors;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetConnectorsResult(
            ImmutableArray<Outputs.GetConnectorsConnectorResult> connectors,

            string id)
        {
            Connectors = connectors;
            Id = id;
        }
    }
}
