// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran
{
    public static class GetDbtProjects
    {
        /// <summary>
        /// This data source returns a list of all dbt Projects within your Fivetran account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myProjects = Fivetran.GetDbtProjects.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetDbtProjectsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDbtProjectsResult>("fivetran:index/getDbtProjects:getDbtProjects", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// This data source returns a list of all dbt Projects within your Fivetran account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myProjects = Fivetran.GetDbtProjects.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDbtProjectsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDbtProjectsResult>("fivetran:index/getDbtProjects:getDbtProjects", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetDbtProjectsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetDbtProjectsProjectResult> Projects;

        [OutputConstructor]
        private GetDbtProjectsResult(
            string id,

            ImmutableArray<Outputs.GetDbtProjectsProjectResult> projects)
        {
            Id = id;
            Projects = projects;
        }
    }
}
