// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran
{
    public static class GetGroupUsers
    {
        /// <summary>
        /// This data source returns a list of information about all users within a group in your Fivetran account.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var groupUsers = Fivetran.GetGroupUsers.Invoke(new()
        ///     {
        ///         Id = "anonymous_mystery",
        ///     });
        /// 
        /// });
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetGroupUsersResult> InvokeAsync(GetGroupUsersArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGroupUsersResult>("fivetran:index/getGroupUsers:getGroupUsers", args ?? new GetGroupUsersArgs(), options.WithDefaults());

        /// <summary>
        /// This data source returns a list of information about all users within a group in your Fivetran account.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var groupUsers = Fivetran.GetGroupUsers.Invoke(new()
        ///     {
        ///         Id = "anonymous_mystery",
        ///     });
        /// 
        /// });
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetGroupUsersResult> Invoke(GetGroupUsersInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupUsersResult>("fivetran:index/getGroupUsers:getGroupUsers", args ?? new GetGroupUsersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGroupUsersArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier for the user within the account.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("users")]
        private List<Inputs.GetGroupUsersUserArgs>? _users;
        public List<Inputs.GetGroupUsersUserArgs> Users
        {
            get => _users ?? (_users = new List<Inputs.GetGroupUsersUserArgs>());
            set => _users = value;
        }

        public GetGroupUsersArgs()
        {
        }
        public static new GetGroupUsersArgs Empty => new GetGroupUsersArgs();
    }

    public sealed class GetGroupUsersInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier for the user within the account.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("users")]
        private InputList<Inputs.GetGroupUsersUserInputArgs>? _users;
        public InputList<Inputs.GetGroupUsersUserInputArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.GetGroupUsersUserInputArgs>());
            set => _users = value;
        }

        public GetGroupUsersInvokeArgs()
        {
        }
        public static new GetGroupUsersInvokeArgs Empty => new GetGroupUsersInvokeArgs();
    }


    [OutputType]
    public sealed class GetGroupUsersResult
    {
        /// <summary>
        /// The unique identifier for the group within the Fivetran system. Data-source will represent a set of users who has membership in this group.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetGroupUsersUserResult> Users;

        [OutputConstructor]
        private GetGroupUsersResult(
            string id,

            ImmutableArray<Outputs.GetGroupUsersUserResult> users)
        {
            Id = id;
            Users = users;
        }
    }
}
