// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran
{
    public static class GetPrivateLink
    {
        /// <summary>
        /// This data source returns a private link object.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var privateLink = Fivetran.GetPrivateLink.Invoke(new()
        ///     {
        ///         Id = "private_link_id",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetPrivateLinkResult> InvokeAsync(GetPrivateLinkArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPrivateLinkResult>("fivetran:index/getPrivateLink:getPrivateLink", args ?? new GetPrivateLinkArgs(), options.WithDefaults());

        /// <summary>
        /// This data source returns a private link object.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var privateLink = Fivetran.GetPrivateLink.Invoke(new()
        ///     {
        ///         Id = "private_link_id",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPrivateLinkResult> Invoke(GetPrivateLinkInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivateLinkResult>("fivetran:index/getPrivateLink:getPrivateLink", args ?? new GetPrivateLinkInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// This data source returns a private link object.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Fivetran = Pulumi.Fivetran;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var privateLink = Fivetran.GetPrivateLink.Invoke(new()
        ///     {
        ///         Id = "private_link_id",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPrivateLinkResult> Invoke(GetPrivateLinkInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivateLinkResult>("fivetran:index/getPrivateLink:getPrivateLink", args ?? new GetPrivateLinkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrivateLinkArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier for the private link within the Fivetran system.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetPrivateLinkArgs()
        {
        }
        public static new GetPrivateLinkArgs Empty => new GetPrivateLinkArgs();
    }

    public sealed class GetPrivateLinkInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier for the private link within the Fivetran system.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetPrivateLinkInvokeArgs()
        {
        }
        public static new GetPrivateLinkInvokeArgs Empty => new GetPrivateLinkInvokeArgs();
    }


    [OutputType]
    public sealed class GetPrivateLinkResult
    {
        /// <summary>
        /// The cloud provider name.
        /// </summary>
        public readonly string CloudProvider;
        /// <summary>
        /// Configuration.
        /// </summary>
        public readonly ImmutableDictionary<string, string> ConfigMap;
        /// <summary>
        /// The date and time the membership was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The unique identifier for the User within the Fivetran system.
        /// </summary>
        public readonly string CreatedBy;
        /// <summary>
        /// The unique identifier for the private link within the Fivetran system.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The private link name within the account. The name must start with a letter or underscore and can only contain letters, numbers, or underscores. Maximum size of name is 23 characters.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Data processing location. This is where Fivetran will operate and run computation on data.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Service type.
        /// </summary>
        public readonly string Service;
        /// <summary>
        /// The state of the private link.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// The state of the private link.
        /// </summary>
        public readonly string StateSummary;

        [OutputConstructor]
        private GetPrivateLinkResult(
            string cloudProvider,

            ImmutableDictionary<string, string> configMap,

            string createdAt,

            string createdBy,

            string id,

            string name,

            string region,

            string service,

            string state,

            string stateSummary)
        {
            CloudProvider = cloudProvider;
            ConfigMap = configMap;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Id = id;
            Name = name;
            Region = region;
            Service = service;
            State = state;
            StateSummary = stateSummary;
        }
    }
}
