// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran
{
    /// <summary>
    /// This resource allows you to create, update, and delete group membership for teams
    /// 
    /// ## Import
    /// 
    /// 1. To import an existing `fivetran_team_group_membership` resource into your Terraform state, you need to get `team_id` and `group_id` You can retrieve all teams using the [fivetran_teams data source](/docs/data-sources/teams). 2. Define an empty resource in your `.tf` configurationhcl resource "fivetran_team_group_membership" "my_imported_fivetran_team_group_membership" { }
    /// 
    /// ```sh
    ///  $ pulumi import fivetran:index/teamGroupMembership:TeamGroupMembership
    /// 
    /// Run the `terraform import` command
    /// ```
    /// 
    /// ```sh
    ///  $ pulumi import fivetran:index/teamGroupMembership:TeamGroupMembership my_imported_fivetran_team_group_membership {team_id}
    /// ```
    /// 
    ///  4. Use the `terraform state show` command to get the values from the stateterraform state show 'fivetran_team_group_membership.my_imported_fivetran_team_group_membership' 5. Copy the values and paste them to your `.tf` configuration.
    /// </summary>
    [FivetranResourceType("fivetran:index/teamGroupMembership:TeamGroupMembership")]
    public partial class TeamGroupMembership : global::Pulumi.CustomResource
    {
        [Output("groups")]
        public Output<ImmutableArray<Outputs.TeamGroupMembershipGroup>> Groups { get; private set; } = null!;

        /// <summary>
        /// The unique identifier for the team within your account.
        /// </summary>
        [Output("teamId")]
        public Output<string> TeamId { get; private set; } = null!;


        /// <summary>
        /// Create a TeamGroupMembership resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TeamGroupMembership(string name, TeamGroupMembershipArgs args, CustomResourceOptions? options = null)
            : base("fivetran:index/teamGroupMembership:TeamGroupMembership", name, args ?? new TeamGroupMembershipArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TeamGroupMembership(string name, Input<string> id, TeamGroupMembershipState? state = null, CustomResourceOptions? options = null)
            : base("fivetran:index/teamGroupMembership:TeamGroupMembership", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/footholdtech/pulumi-fivetran",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TeamGroupMembership resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TeamGroupMembership Get(string name, Input<string> id, TeamGroupMembershipState? state = null, CustomResourceOptions? options = null)
        {
            return new TeamGroupMembership(name, id, state, options);
        }
    }

    public sealed class TeamGroupMembershipArgs : global::Pulumi.ResourceArgs
    {
        [Input("groups")]
        private InputList<Inputs.TeamGroupMembershipGroupArgs>? _groups;
        public InputList<Inputs.TeamGroupMembershipGroupArgs> Groups
        {
            get => _groups ?? (_groups = new InputList<Inputs.TeamGroupMembershipGroupArgs>());
            set => _groups = value;
        }

        /// <summary>
        /// The unique identifier for the team within your account.
        /// </summary>
        [Input("teamId", required: true)]
        public Input<string> TeamId { get; set; } = null!;

        public TeamGroupMembershipArgs()
        {
        }
        public static new TeamGroupMembershipArgs Empty => new TeamGroupMembershipArgs();
    }

    public sealed class TeamGroupMembershipState : global::Pulumi.ResourceArgs
    {
        [Input("groups")]
        private InputList<Inputs.TeamGroupMembershipGroupGetArgs>? _groups;
        public InputList<Inputs.TeamGroupMembershipGroupGetArgs> Groups
        {
            get => _groups ?? (_groups = new InputList<Inputs.TeamGroupMembershipGroupGetArgs>());
            set => _groups = value;
        }

        /// <summary>
        /// The unique identifier for the team within your account.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        public TeamGroupMembershipState()
        {
        }
        public static new TeamGroupMembershipState Empty => new TeamGroupMembershipState();
    }
}
