# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .connector import *
from .connector_schedule import *
from .connector_schema_config import *
from .dbt_project import *
from .dbt_transformation import *
from .destination import *
from .get_connector import *
from .get_connectors_metadata import *
from .get_dbt_models import *
from .get_dbt_project import *
from .get_dbt_projects import *
from .get_dbt_transformation import *
from .get_destination import *
from .get_group import *
from .get_group_connectors import *
from .get_group_users import *
from .get_groups import *
from .get_user import *
from .get_users import *
from .get_webhook import *
from .get_webhooks import *
from .group import *
from .group_users import *
from .provider import *
from .user import *
from .webhook import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import footholdtech_fivetran.config as __config
    config = __config
else:
    config = _utilities.lazy_import('footholdtech_fivetran.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "fivetran",
  "mod": "index/connector",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/connector:Connector": "Connector"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/connectorSchedule",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/connectorSchedule:ConnectorSchedule": "ConnectorSchedule"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/connectorSchemaConfig",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/connectorSchemaConfig:ConnectorSchemaConfig": "ConnectorSchemaConfig"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/dbtProject",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/dbtProject:DbtProject": "DbtProject"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/dbtTransformation",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/dbtTransformation:DbtTransformation": "DbtTransformation"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/destination",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/destination:Destination": "Destination"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/group",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/group:Group": "Group"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/groupUsers",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/groupUsers:GroupUsers": "GroupUsers"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/user",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/user:User": "User"
  }
 },
 {
  "pkg": "fivetran",
  "mod": "index/webhook",
  "fqn": "footholdtech_fivetran",
  "classes": {
   "fivetran:index/webhook:Webhook": "Webhook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "fivetran",
  "token": "pulumi:providers:fivetran",
  "fqn": "footholdtech_fivetran",
  "class": "Provider"
 }
]
"""
)
