# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetConnectionFingerprintsResult',
    'AwaitableGetConnectionFingerprintsResult',
    'get_connection_fingerprints',
    'get_connection_fingerprints_output',
]

@pulumi.output_type
class GetConnectionFingerprintsResult:
    """
    A collection of values returned by getConnectionFingerprints.
    """
    def __init__(__self__, fingerprints=None, id=None):
        if fingerprints and not isinstance(fingerprints, list):
            raise TypeError("Expected argument 'fingerprints' to be a list")
        pulumi.set(__self__, "fingerprints", fingerprints)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def fingerprints(self) -> Optional[Sequence['outputs.GetConnectionFingerprintsFingerprintResult']]:
        return pulumi.get(self, "fingerprints")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The unique identifier for the target connection within the Fivetran system.
        """
        return pulumi.get(self, "id")


class AwaitableGetConnectionFingerprintsResult(GetConnectionFingerprintsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetConnectionFingerprintsResult(
            fingerprints=self.fingerprints,
            id=self.id)


def get_connection_fingerprints(fingerprints: Optional[Sequence[Union['GetConnectionFingerprintsFingerprintArgs', 'GetConnectionFingerprintsFingerprintArgsDict']]] = None,
                                id: Optional[str] = None,
                                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetConnectionFingerprintsResult:
    """
    This data source returns a list of SSH fingerprints approved for specified connection.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_fivetran as fivetran

    connection_fingerprints = fivetran.get_connection_fingerprints(id="connection_id")
    ```


    :param str id: The unique identifier for the target connection within the Fivetran system.
    """
    __args__ = dict()
    __args__['fingerprints'] = fingerprints
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fivetran:index/getConnectionFingerprints:getConnectionFingerprints', __args__, opts=opts, typ=GetConnectionFingerprintsResult).value

    return AwaitableGetConnectionFingerprintsResult(
        fingerprints=pulumi.get(__ret__, 'fingerprints'),
        id=pulumi.get(__ret__, 'id'))
def get_connection_fingerprints_output(fingerprints: Optional[pulumi.Input[Optional[Sequence[Union['GetConnectionFingerprintsFingerprintArgs', 'GetConnectionFingerprintsFingerprintArgsDict']]]]] = None,
                                       id: Optional[pulumi.Input[str]] = None,
                                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetConnectionFingerprintsResult]:
    """
    This data source returns a list of SSH fingerprints approved for specified connection.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_fivetran as fivetran

    connection_fingerprints = fivetran.get_connection_fingerprints(id="connection_id")
    ```


    :param str id: The unique identifier for the target connection within the Fivetran system.
    """
    __args__ = dict()
    __args__['fingerprints'] = fingerprints
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fivetran:index/getConnectionFingerprints:getConnectionFingerprints', __args__, opts=opts, typ=GetConnectionFingerprintsResult)
    return __ret__.apply(lambda __response__: GetConnectionFingerprintsResult(
        fingerprints=pulumi.get(__response__, 'fingerprints'),
        id=pulumi.get(__response__, 'id')))
