# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProxyAgentArgs', 'ProxyAgent']

@pulumi.input_type
class ProxyAgentArgs:
    def __init__(__self__, *,
                 display_name: pulumi.Input[builtins.str],
                 group_region: pulumi.Input[builtins.str],
                 regeneration_counter: Optional[pulumi.Input[builtins.int]] = None):
        """
        The set of arguments for constructing a ProxyAgent resource.
        :param pulumi.Input[builtins.str] display_name: Proxy agent name.
        :param pulumi.Input[builtins.str] group_region: Data processing location. This is where Fivetran will operate and run computation on data.
        :param pulumi.Input[builtins.int] regeneration_counter: Determines whether regenerarion secrets needs to be performed.
        """
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "group_region", group_region)
        if regeneration_counter is not None:
            pulumi.set(__self__, "regeneration_counter", regeneration_counter)

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[builtins.str]:
        """
        Proxy agent name.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "display_name", value)

    @property
    @pulumi.getter(name="groupRegion")
    def group_region(self) -> pulumi.Input[builtins.str]:
        """
        Data processing location. This is where Fivetran will operate and run computation on data.
        """
        return pulumi.get(self, "group_region")

    @group_region.setter
    def group_region(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "group_region", value)

    @property
    @pulumi.getter(name="regenerationCounter")
    def regeneration_counter(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Determines whether regenerarion secrets needs to be performed.
        """
        return pulumi.get(self, "regeneration_counter")

    @regeneration_counter.setter
    def regeneration_counter(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "regeneration_counter", value)


@pulumi.input_type
class _ProxyAgentState:
    def __init__(__self__, *,
                 client_cert: Optional[pulumi.Input[builtins.str]] = None,
                 client_private_key: Optional[pulumi.Input[builtins.str]] = None,
                 created_by: Optional[pulumi.Input[builtins.str]] = None,
                 display_name: Optional[pulumi.Input[builtins.str]] = None,
                 group_region: Optional[pulumi.Input[builtins.str]] = None,
                 regeneration_counter: Optional[pulumi.Input[builtins.int]] = None,
                 registred_at: Optional[pulumi.Input[builtins.str]] = None,
                 token: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering ProxyAgent resources.
        :param pulumi.Input[builtins.str] client_cert: Client certificate.
        :param pulumi.Input[builtins.str] client_private_key: Client private key.
        :param pulumi.Input[builtins.str] created_by: The actor who created the proxy agent.
        :param pulumi.Input[builtins.str] display_name: Proxy agent name.
        :param pulumi.Input[builtins.str] group_region: Data processing location. This is where Fivetran will operate and run computation on data.
        :param pulumi.Input[builtins.int] regeneration_counter: Determines whether regenerarion secrets needs to be performed.
        :param pulumi.Input[builtins.str] registred_at: The timestamp of the time the proxy agent was created in your account.
        :param pulumi.Input[builtins.str] token: The auth token.
        """
        if client_cert is not None:
            pulumi.set(__self__, "client_cert", client_cert)
        if client_private_key is not None:
            pulumi.set(__self__, "client_private_key", client_private_key)
        if created_by is not None:
            pulumi.set(__self__, "created_by", created_by)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if group_region is not None:
            pulumi.set(__self__, "group_region", group_region)
        if regeneration_counter is not None:
            pulumi.set(__self__, "regeneration_counter", regeneration_counter)
        if registred_at is not None:
            pulumi.set(__self__, "registred_at", registred_at)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @property
    @pulumi.getter(name="clientCert")
    def client_cert(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Client certificate.
        """
        return pulumi.get(self, "client_cert")

    @client_cert.setter
    def client_cert(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "client_cert", value)

    @property
    @pulumi.getter(name="clientPrivateKey")
    def client_private_key(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Client private key.
        """
        return pulumi.get(self, "client_private_key")

    @client_private_key.setter
    def client_private_key(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "client_private_key", value)

    @property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The actor who created the proxy agent.
        """
        return pulumi.get(self, "created_by")

    @created_by.setter
    def created_by(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "created_by", value)

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Proxy agent name.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "display_name", value)

    @property
    @pulumi.getter(name="groupRegion")
    def group_region(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Data processing location. This is where Fivetran will operate and run computation on data.
        """
        return pulumi.get(self, "group_region")

    @group_region.setter
    def group_region(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "group_region", value)

    @property
    @pulumi.getter(name="regenerationCounter")
    def regeneration_counter(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Determines whether regenerarion secrets needs to be performed.
        """
        return pulumi.get(self, "regeneration_counter")

    @regeneration_counter.setter
    def regeneration_counter(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "regeneration_counter", value)

    @property
    @pulumi.getter(name="registredAt")
    def registred_at(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The timestamp of the time the proxy agent was created in your account.
        """
        return pulumi.get(self, "registred_at")

    @registred_at.setter
    def registred_at(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "registred_at", value)

    @property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The auth token.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("fivetran:index/proxyAgent:ProxyAgent")
class ProxyAgent(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 display_name: Optional[pulumi.Input[builtins.str]] = None,
                 group_region: Optional[pulumi.Input[builtins.str]] = None,
                 regeneration_counter: Optional[pulumi.Input[builtins.int]] = None,
                 __props__=None):
        """
        This resource allows you to create, update, and delete proxy agent.

        > NOTE: Proxy Agents created after 2025-06-10 must be run using the Proxy Agent bundled in high-volume agent version 6.1.0/79 or later, else  connections will fail. EOL for versions bundled with eariler than 6.1.0/79 will occur on 2025-10-08.

        ## Example Usage

        ```python
        import pulumi
        import footholdtech_fivetran as fivetran

        test_proxy_agent = fivetran.ProxyAgent("test_proxy_agent",
            display_name="display_name",
            group_region="group_region")
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] display_name: Proxy agent name.
        :param pulumi.Input[builtins.str] group_region: Data processing location. This is where Fivetran will operate and run computation on data.
        :param pulumi.Input[builtins.int] regeneration_counter: Determines whether regenerarion secrets needs to be performed.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProxyAgentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        This resource allows you to create, update, and delete proxy agent.

        > NOTE: Proxy Agents created after 2025-06-10 must be run using the Proxy Agent bundled in high-volume agent version 6.1.0/79 or later, else  connections will fail. EOL for versions bundled with eariler than 6.1.0/79 will occur on 2025-10-08.

        ## Example Usage

        ```python
        import pulumi
        import footholdtech_fivetran as fivetran

        test_proxy_agent = fivetran.ProxyAgent("test_proxy_agent",
            display_name="display_name",
            group_region="group_region")
        ```

        :param str resource_name: The name of the resource.
        :param ProxyAgentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProxyAgentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 display_name: Optional[pulumi.Input[builtins.str]] = None,
                 group_region: Optional[pulumi.Input[builtins.str]] = None,
                 regeneration_counter: Optional[pulumi.Input[builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProxyAgentArgs.__new__(ProxyAgentArgs)

            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            if group_region is None and not opts.urn:
                raise TypeError("Missing required property 'group_region'")
            __props__.__dict__["group_region"] = group_region
            __props__.__dict__["regeneration_counter"] = regeneration_counter
            __props__.__dict__["client_cert"] = None
            __props__.__dict__["client_private_key"] = None
            __props__.__dict__["created_by"] = None
            __props__.__dict__["registred_at"] = None
            __props__.__dict__["token"] = None
        super(ProxyAgent, __self__).__init__(
            'fivetran:index/proxyAgent:ProxyAgent',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            client_cert: Optional[pulumi.Input[builtins.str]] = None,
            client_private_key: Optional[pulumi.Input[builtins.str]] = None,
            created_by: Optional[pulumi.Input[builtins.str]] = None,
            display_name: Optional[pulumi.Input[builtins.str]] = None,
            group_region: Optional[pulumi.Input[builtins.str]] = None,
            regeneration_counter: Optional[pulumi.Input[builtins.int]] = None,
            registred_at: Optional[pulumi.Input[builtins.str]] = None,
            token: Optional[pulumi.Input[builtins.str]] = None) -> 'ProxyAgent':
        """
        Get an existing ProxyAgent resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] client_cert: Client certificate.
        :param pulumi.Input[builtins.str] client_private_key: Client private key.
        :param pulumi.Input[builtins.str] created_by: The actor who created the proxy agent.
        :param pulumi.Input[builtins.str] display_name: Proxy agent name.
        :param pulumi.Input[builtins.str] group_region: Data processing location. This is where Fivetran will operate and run computation on data.
        :param pulumi.Input[builtins.int] regeneration_counter: Determines whether regenerarion secrets needs to be performed.
        :param pulumi.Input[builtins.str] registred_at: The timestamp of the time the proxy agent was created in your account.
        :param pulumi.Input[builtins.str] token: The auth token.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProxyAgentState.__new__(_ProxyAgentState)

        __props__.__dict__["client_cert"] = client_cert
        __props__.__dict__["client_private_key"] = client_private_key
        __props__.__dict__["created_by"] = created_by
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["group_region"] = group_region
        __props__.__dict__["regeneration_counter"] = regeneration_counter
        __props__.__dict__["registred_at"] = registred_at
        __props__.__dict__["token"] = token
        return ProxyAgent(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="clientCert")
    def client_cert(self) -> pulumi.Output[builtins.str]:
        """
        Client certificate.
        """
        return pulumi.get(self, "client_cert")

    @property
    @pulumi.getter(name="clientPrivateKey")
    def client_private_key(self) -> pulumi.Output[builtins.str]:
        """
        Client private key.
        """
        return pulumi.get(self, "client_private_key")

    @property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> pulumi.Output[builtins.str]:
        """
        The actor who created the proxy agent.
        """
        return pulumi.get(self, "created_by")

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[builtins.str]:
        """
        Proxy agent name.
        """
        return pulumi.get(self, "display_name")

    @property
    @pulumi.getter(name="groupRegion")
    def group_region(self) -> pulumi.Output[builtins.str]:
        """
        Data processing location. This is where Fivetran will operate and run computation on data.
        """
        return pulumi.get(self, "group_region")

    @property
    @pulumi.getter(name="regenerationCounter")
    def regeneration_counter(self) -> pulumi.Output[builtins.int]:
        """
        Determines whether regenerarion secrets needs to be performed.
        """
        return pulumi.get(self, "regeneration_counter")

    @property
    @pulumi.getter(name="registredAt")
    def registred_at(self) -> pulumi.Output[builtins.str]:
        """
        The timestamp of the time the proxy agent was created in your account.
        """
        return pulumi.get(self, "registred_at")

    @property
    @pulumi.getter
    def token(self) -> pulumi.Output[builtins.str]:
        """
        The auth token.
        """
        return pulumi.get(self, "token")

