// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorSchemaConfigSchemaTable
    {
        public readonly ImmutableArray<Outputs.ConnectorSchemaConfigSchemaTableColumn> Columns;
        /// <summary>
        /// The boolean value specifying whether the sync for the schema into the destination is enabled.
        /// </summary>
        public readonly string? Enabled;
        /// <summary>
        /// The schema name within your destination in accordance with Fivetran conventional rules.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// This field appears in the response if the connector supports switching sync modes for tables.
        /// </summary>
        public readonly string? SyncMode;

        [OutputConstructor]
        private ConnectorSchemaConfigSchemaTable(
            ImmutableArray<Outputs.ConnectorSchemaConfigSchemaTableColumn> columns,

            string? enabled,

            string name,

            string? syncMode)
        {
            Columns = columns;
            Enabled = enabled;
            Name = name;
            SyncMode = syncMode;
        }
    }
}
