// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorConfigProjectCredential
    {
        public readonly string? ApiKey;
        public readonly string? Project;
        public readonly string? SecretKey;

        [OutputConstructor]
        private ConnectorConfigProjectCredential(
            string? apiKey,

            string? project,

            string? secretKey)
        {
            ApiKey = apiKey;
            Project = project;
            SecretKey = secretKey;
        }
    }
}
