// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorSchemaConfigSchemas
    {
        /// <summary>
        /// The boolean value specifying whether the sync for the schema into the destination is enabled.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Map of table configurations.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.ConnectorSchemaConfigSchemasTables>? Tables;

        [OutputConstructor]
        private ConnectorSchemaConfigSchemas(
            bool? enabled,

            ImmutableDictionary<string, Outputs.ConnectorSchemaConfigSchemasTables>? tables)
        {
            Enabled = enabled;
            Tables = tables;
        }
    }
}
