// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetGroupConnectorsConnectorStatusResult
    {
        public readonly bool IsHistoricalSync;
        public readonly string SetupState;
        public readonly string SyncState;
        public readonly ImmutableArray<Outputs.GetGroupConnectorsConnectorStatusTaskResult> Tasks;
        public readonly string UpdateState;
        public readonly ImmutableArray<Outputs.GetGroupConnectorsConnectorStatusWarningResult> Warnings;

        [OutputConstructor]
        private GetGroupConnectorsConnectorStatusResult(
            bool isHistoricalSync,

            string setupState,

            string syncState,

            ImmutableArray<Outputs.GetGroupConnectorsConnectorStatusTaskResult> tasks,

            string updateState,

            ImmutableArray<Outputs.GetGroupConnectorsConnectorStatusWarningResult> warnings)
        {
            IsHistoricalSync = isHistoricalSync;
            SetupState = setupState;
            SyncState = syncState;
            Tasks = tasks;
            UpdateState = updateState;
            Warnings = warnings;
        }
    }
}
