// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetQuickstartPackagesPackageResult
    {
        /// <summary>
        /// The set of connector types
        /// </summary>
        public readonly ImmutableArray<string> ConnectorTypes;
        /// <summary>
        /// The unique identifier for the Quickstart transformation package definition within the Fivetran system
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The Quickstart transformation package name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The list of transformation output models
        /// </summary>
        public readonly ImmutableArray<string> OutputModelNames;
        /// <summary>
        /// The Quickstart package definition version
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetQuickstartPackagesPackageResult(
            ImmutableArray<string> connectorTypes,

            string id,

            string name,

            ImmutableArray<string> outputModelNames,

            string version)
        {
            ConnectorTypes = connectorTypes;
            Id = id;
            Name = name;
            OutputModelNames = outputModelNames;
            Version = version;
        }
    }
}
