// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetTransformationsTransformationTransformationConfigStepResult
    {
        /// <summary>
        /// The dbt command in the transformation step
        /// </summary>
        public readonly string Command;
        /// <summary>
        /// The step name
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetTransformationsTransformationTransformationConfigStepResult(
            string command,

            string name)
        {
            Command = command;
            Name = name;
        }
    }
}
