// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetTeamConnectionMembershipsConnectionResult
    {
        /// <summary>
        /// The connection unique identifier
        /// </summary>
        public readonly string ConnectionId;
        /// <summary>
        /// The date and time the membership was created
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The team's role that links the team and the connection
        /// </summary>
        public readonly string Role;

        [OutputConstructor]
        private GetTeamConnectionMembershipsConnectionResult(
            string connectionId,

            string createdAt,

            string role)
        {
            ConnectionId = connectionId;
            CreatedAt = createdAt;
            Role = role;
        }
    }
}
