// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetUserConnectorMembershipsConnectorResult
    {
        /// <summary>
        /// The connector unique identifier
        /// </summary>
        public readonly string ConnectorId;
        /// <summary>
        /// The date and time the membership was created
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The user's role that links the user and the connector
        /// </summary>
        public readonly string Role;

        [OutputConstructor]
        private GetUserConnectorMembershipsConnectorResult(
            string connectorId,

            string createdAt,

            string role)
        {
            ConnectorId = connectorId;
            CreatedAt = createdAt;
            Role = role;
        }
    }
}
