// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Outputs
{

    [OutputType]
    public sealed class TeamUserMembershipUser
    {
        /// <summary>
        /// The team's role that links the team and the user
        /// </summary>
        public readonly string Role;
        /// <summary>
        /// The user unique identifier
        /// </summary>
        public readonly string UserId;

        [OutputConstructor]
        private TeamUserMembershipUser(
            string role,

            string userId)
        {
            Role = role;
            UserId = userId;
        }
    }
}
