// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConnectorAuthClientAccessArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConnectorAuthClientAccessArgs Empty = new ConnectorAuthClientAccessArgs();

    @Import(name="clientId")
    private @Nullable Output<String> clientId;

    public Optional<Output<String>> clientId() {
        return Optional.ofNullable(this.clientId);
    }

    @Import(name="clientSecret")
    private @Nullable Output<String> clientSecret;

    public Optional<Output<String>> clientSecret() {
        return Optional.ofNullable(this.clientSecret);
    }

    @Import(name="developerToken")
    private @Nullable Output<String> developerToken;

    public Optional<Output<String>> developerToken() {
        return Optional.ofNullable(this.developerToken);
    }

    @Import(name="userAgent")
    private @Nullable Output<String> userAgent;

    public Optional<Output<String>> userAgent() {
        return Optional.ofNullable(this.userAgent);
    }

    private ConnectorAuthClientAccessArgs() {}

    private ConnectorAuthClientAccessArgs(ConnectorAuthClientAccessArgs $) {
        this.clientId = $.clientId;
        this.clientSecret = $.clientSecret;
        this.developerToken = $.developerToken;
        this.userAgent = $.userAgent;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConnectorAuthClientAccessArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConnectorAuthClientAccessArgs $;

        public Builder() {
            $ = new ConnectorAuthClientAccessArgs();
        }

        public Builder(ConnectorAuthClientAccessArgs defaults) {
            $ = new ConnectorAuthClientAccessArgs(Objects.requireNonNull(defaults));
        }

        public Builder clientId(@Nullable Output<String> clientId) {
            $.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            return clientId(Output.of(clientId));
        }

        public Builder clientSecret(@Nullable Output<String> clientSecret) {
            $.clientSecret = clientSecret;
            return this;
        }

        public Builder clientSecret(String clientSecret) {
            return clientSecret(Output.of(clientSecret));
        }

        public Builder developerToken(@Nullable Output<String> developerToken) {
            $.developerToken = developerToken;
            return this;
        }

        public Builder developerToken(String developerToken) {
            return developerToken(Output.of(developerToken));
        }

        public Builder userAgent(@Nullable Output<String> userAgent) {
            $.userAgent = userAgent;
            return this;
        }

        public Builder userAgent(String userAgent) {
            return userAgent(Output.of(userAgent));
        }

        public ConnectorAuthClientAccessArgs build() {
            return $;
        }
    }

}
