// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class GetConnectorConfigReport extends com.pulumi.resources.InvokeArgs {

    public static final GetConnectorConfigReport Empty = new GetConnectorConfigReport();

    @Import(name="aggregation", required=true)
    private String aggregation;

    public String aggregation() {
        return this.aggregation;
    }

    @Import(name="attributes", required=true)
    private List<String> attributes;

    public List<String> attributes() {
        return this.attributes;
    }

    @Import(name="configType", required=true)
    private String configType;

    public String configType() {
        return this.configType;
    }

    @Import(name="dimensions", required=true)
    private List<String> dimensions;

    public List<String> dimensions() {
        return this.dimensions;
    }

    @Import(name="fields", required=true)
    private List<String> fields;

    public List<String> fields() {
        return this.fields;
    }

    @Import(name="filter", required=true)
    private String filter;

    public String filter() {
        return this.filter;
    }

    @Import(name="filterFieldName", required=true)
    private String filterFieldName;

    public String filterFieldName() {
        return this.filterFieldName;
    }

    @Import(name="filterType", required=true)
    private String filterType;

    public String filterType() {
        return this.filterType;
    }

    @Import(name="filterValue", required=true)
    private String filterValue;

    public String filterValue() {
        return this.filterValue;
    }

    @Import(name="metrics", required=true)
    private List<String> metrics;

    public List<String> metrics() {
        return this.metrics;
    }

    @Import(name="prebuiltReport", required=true)
    private String prebuiltReport;

    public String prebuiltReport() {
        return this.prebuiltReport;
    }

    @Import(name="reportType", required=true)
    private String reportType;

    public String reportType() {
        return this.reportType;
    }

    @Import(name="rollbackWindow", required=true)
    private String rollbackWindow;

    public String rollbackWindow() {
        return this.rollbackWindow;
    }

    @Import(name="searchTypes", required=true)
    private List<String> searchTypes;

    public List<String> searchTypes() {
        return this.searchTypes;
    }

    @Import(name="segmentIds", required=true)
    private List<String> segmentIds;

    public List<String> segmentIds() {
        return this.segmentIds;
    }

    @Import(name="segments", required=true)
    private List<String> segments;

    public List<String> segments() {
        return this.segments;
    }

    @Import(name="table", required=true)
    private String table;

    public String table() {
        return this.table;
    }

    private GetConnectorConfigReport() {}

    private GetConnectorConfigReport(GetConnectorConfigReport $) {
        this.aggregation = $.aggregation;
        this.attributes = $.attributes;
        this.configType = $.configType;
        this.dimensions = $.dimensions;
        this.fields = $.fields;
        this.filter = $.filter;
        this.filterFieldName = $.filterFieldName;
        this.filterType = $.filterType;
        this.filterValue = $.filterValue;
        this.metrics = $.metrics;
        this.prebuiltReport = $.prebuiltReport;
        this.reportType = $.reportType;
        this.rollbackWindow = $.rollbackWindow;
        this.searchTypes = $.searchTypes;
        this.segmentIds = $.segmentIds;
        this.segments = $.segments;
        this.table = $.table;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConnectorConfigReport defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConnectorConfigReport $;

        public Builder() {
            $ = new GetConnectorConfigReport();
        }

        public Builder(GetConnectorConfigReport defaults) {
            $ = new GetConnectorConfigReport(Objects.requireNonNull(defaults));
        }

        public Builder aggregation(String aggregation) {
            $.aggregation = aggregation;
            return this;
        }

        public Builder attributes(List<String> attributes) {
            $.attributes = attributes;
            return this;
        }

        public Builder attributes(String... attributes) {
            return attributes(List.of(attributes));
        }

        public Builder configType(String configType) {
            $.configType = configType;
            return this;
        }

        public Builder dimensions(List<String> dimensions) {
            $.dimensions = dimensions;
            return this;
        }

        public Builder dimensions(String... dimensions) {
            return dimensions(List.of(dimensions));
        }

        public Builder fields(List<String> fields) {
            $.fields = fields;
            return this;
        }

        public Builder fields(String... fields) {
            return fields(List.of(fields));
        }

        public Builder filter(String filter) {
            $.filter = filter;
            return this;
        }

        public Builder filterFieldName(String filterFieldName) {
            $.filterFieldName = filterFieldName;
            return this;
        }

        public Builder filterType(String filterType) {
            $.filterType = filterType;
            return this;
        }

        public Builder filterValue(String filterValue) {
            $.filterValue = filterValue;
            return this;
        }

        public Builder metrics(List<String> metrics) {
            $.metrics = metrics;
            return this;
        }

        public Builder metrics(String... metrics) {
            return metrics(List.of(metrics));
        }

        public Builder prebuiltReport(String prebuiltReport) {
            $.prebuiltReport = prebuiltReport;
            return this;
        }

        public Builder reportType(String reportType) {
            $.reportType = reportType;
            return this;
        }

        public Builder rollbackWindow(String rollbackWindow) {
            $.rollbackWindow = rollbackWindow;
            return this;
        }

        public Builder searchTypes(List<String> searchTypes) {
            $.searchTypes = searchTypes;
            return this;
        }

        public Builder searchTypes(String... searchTypes) {
            return searchTypes(List.of(searchTypes));
        }

        public Builder segmentIds(List<String> segmentIds) {
            $.segmentIds = segmentIds;
            return this;
        }

        public Builder segmentIds(String... segmentIds) {
            return segmentIds(List.of(segmentIds));
        }

        public Builder segments(List<String> segments) {
            $.segments = segments;
            return this;
        }

        public Builder segments(String... segments) {
            return segments(List.of(segments));
        }

        public Builder table(String table) {
            $.table = table;
            return this;
        }

        public GetConnectorConfigReport build() {
            $.aggregation = Objects.requireNonNull($.aggregation, "expected parameter 'aggregation' to be non-null");
            $.attributes = Objects.requireNonNull($.attributes, "expected parameter 'attributes' to be non-null");
            $.configType = Objects.requireNonNull($.configType, "expected parameter 'configType' to be non-null");
            $.dimensions = Objects.requireNonNull($.dimensions, "expected parameter 'dimensions' to be non-null");
            $.fields = Objects.requireNonNull($.fields, "expected parameter 'fields' to be non-null");
            $.filter = Objects.requireNonNull($.filter, "expected parameter 'filter' to be non-null");
            $.filterFieldName = Objects.requireNonNull($.filterFieldName, "expected parameter 'filterFieldName' to be non-null");
            $.filterType = Objects.requireNonNull($.filterType, "expected parameter 'filterType' to be non-null");
            $.filterValue = Objects.requireNonNull($.filterValue, "expected parameter 'filterValue' to be non-null");
            $.metrics = Objects.requireNonNull($.metrics, "expected parameter 'metrics' to be non-null");
            $.prebuiltReport = Objects.requireNonNull($.prebuiltReport, "expected parameter 'prebuiltReport' to be non-null");
            $.reportType = Objects.requireNonNull($.reportType, "expected parameter 'reportType' to be non-null");
            $.rollbackWindow = Objects.requireNonNull($.rollbackWindow, "expected parameter 'rollbackWindow' to be non-null");
            $.searchTypes = Objects.requireNonNull($.searchTypes, "expected parameter 'searchTypes' to be non-null");
            $.segmentIds = Objects.requireNonNull($.segmentIds, "expected parameter 'segmentIds' to be non-null");
            $.segments = Objects.requireNonNull($.segments, "expected parameter 'segments' to be non-null");
            $.table = Objects.requireNonNull($.table, "expected parameter 'table' to be non-null");
            return $;
        }
    }

}
