// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetDbtProjectsProject extends com.pulumi.resources.InvokeArgs {

    public static final GetDbtProjectsProject Empty = new GetDbtProjectsProject();

    /**
     * The timestamp of when the project was created in your account.
     * 
     */
    @Import(name="createdAt", required=true)
    private String createdAt;

    /**
     * @return The timestamp of when the project was created in your account.
     * 
     */
    public String createdAt() {
        return this.createdAt;
    }

    /**
     * The unique identifier for the User within the Fivetran system who created the DBT Project.
     * 
     */
    @Import(name="createdById", required=true)
    private String createdById;

    /**
     * @return The unique identifier for the User within the Fivetran system who created the DBT Project.
     * 
     */
    public String createdById() {
        return this.createdById;
    }

    /**
     * The name of the group within your account related to the project.
     * 
     */
    @Import(name="groupId", required=true)
    private String groupId;

    /**
     * @return The name of the group within your account related to the project.
     * 
     */
    public String groupId() {
        return this.groupId;
    }

    /**
     * The unique identifier for the dbt project within the Fivetran system.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The unique identifier for the dbt project within the Fivetran system.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetDbtProjectsProject() {}

    private GetDbtProjectsProject(GetDbtProjectsProject $) {
        this.createdAt = $.createdAt;
        this.createdById = $.createdById;
        this.groupId = $.groupId;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDbtProjectsProject defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDbtProjectsProject $;

        public Builder() {
            $ = new GetDbtProjectsProject();
        }

        public Builder(GetDbtProjectsProject defaults) {
            $ = new GetDbtProjectsProject(Objects.requireNonNull(defaults));
        }

        /**
         * @param createdAt The timestamp of when the project was created in your account.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdById The unique identifier for the User within the Fivetran system who created the DBT Project.
         * 
         * @return builder
         * 
         */
        public Builder createdById(String createdById) {
            $.createdById = createdById;
            return this;
        }

        /**
         * @param groupId The name of the group within your account related to the project.
         * 
         * @return builder
         * 
         */
        public Builder groupId(String groupId) {
            $.groupId = groupId;
            return this;
        }

        /**
         * @param id The unique identifier for the dbt project within the Fivetran system.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetDbtProjectsProject build() {
            $.createdAt = Objects.requireNonNull($.createdAt, "expected parameter 'createdAt' to be non-null");
            $.createdById = Objects.requireNonNull($.createdById, "expected parameter 'createdById' to be non-null");
            $.groupId = Objects.requireNonNull($.groupId, "expected parameter 'groupId' to be non-null");
            $.id = Objects.requireNonNull($.id, "expected parameter 'id' to be non-null");
            return $;
        }
    }

}
