// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetTeamGroupMembershipsGroup extends com.pulumi.resources.InvokeArgs {

    public static final GetTeamGroupMembershipsGroup Empty = new GetTeamGroupMembershipsGroup();

    /**
     * The date and time the membership was created
     * 
     */
    @Import(name="createdAt", required=true)
    private String createdAt;

    /**
     * @return The date and time the membership was created
     * 
     */
    public String createdAt() {
        return this.createdAt;
    }

    /**
     * The group unique identifier
     * 
     */
    @Import(name="groupId", required=true)
    private String groupId;

    /**
     * @return The group unique identifier
     * 
     */
    public String groupId() {
        return this.groupId;
    }

    /**
     * The team&#39;s role that links the team and the group
     * 
     */
    @Import(name="role", required=true)
    private String role;

    /**
     * @return The team&#39;s role that links the team and the group
     * 
     */
    public String role() {
        return this.role;
    }

    private GetTeamGroupMembershipsGroup() {}

    private GetTeamGroupMembershipsGroup(GetTeamGroupMembershipsGroup $) {
        this.createdAt = $.createdAt;
        this.groupId = $.groupId;
        this.role = $.role;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTeamGroupMembershipsGroup defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTeamGroupMembershipsGroup $;

        public Builder() {
            $ = new GetTeamGroupMembershipsGroup();
        }

        public Builder(GetTeamGroupMembershipsGroup defaults) {
            $ = new GetTeamGroupMembershipsGroup(Objects.requireNonNull(defaults));
        }

        /**
         * @param createdAt The date and time the membership was created
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param groupId The group unique identifier
         * 
         * @return builder
         * 
         */
        public Builder groupId(String groupId) {
            $.groupId = groupId;
            return this;
        }

        /**
         * @param role The team&#39;s role that links the team and the group
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            $.role = role;
            return this;
        }

        public GetTeamGroupMembershipsGroup build() {
            $.createdAt = Objects.requireNonNull($.createdAt, "expected parameter 'createdAt' to be non-null");
            $.groupId = Objects.requireNonNull($.groupId, "expected parameter 'groupId' to be non-null");
            $.role = Objects.requireNonNull($.role, "expected parameter 'role' to be non-null");
            return $;
        }
    }

}
