// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConnectorAuthClientAccess {
    private @Nullable String clientId;
    private @Nullable String clientSecret;
    private @Nullable String developerToken;
    private @Nullable String userAgent;

    private ConnectorAuthClientAccess() {}
    public Optional<String> clientId() {
        return Optional.ofNullable(this.clientId);
    }
    public Optional<String> clientSecret() {
        return Optional.ofNullable(this.clientSecret);
    }
    public Optional<String> developerToken() {
        return Optional.ofNullable(this.developerToken);
    }
    public Optional<String> userAgent() {
        return Optional.ofNullable(this.userAgent);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConnectorAuthClientAccess defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String clientId;
        private @Nullable String clientSecret;
        private @Nullable String developerToken;
        private @Nullable String userAgent;
        public Builder() {}
        public Builder(ConnectorAuthClientAccess defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.clientId = defaults.clientId;
    	      this.clientSecret = defaults.clientSecret;
    	      this.developerToken = defaults.developerToken;
    	      this.userAgent = defaults.userAgent;
        }

        @CustomType.Setter
        public Builder clientId(@Nullable String clientId) {
            this.clientId = clientId;
            return this;
        }
        @CustomType.Setter
        public Builder clientSecret(@Nullable String clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }
        @CustomType.Setter
        public Builder developerToken(@Nullable String developerToken) {
            this.developerToken = developerToken;
            return this;
        }
        @CustomType.Setter
        public Builder userAgent(@Nullable String userAgent) {
            this.userAgent = userAgent;
            return this;
        }
        public ConnectorAuthClientAccess build() {
            final var o = new ConnectorAuthClientAccess();
            o.clientId = clientId;
            o.clientSecret = clientSecret;
            o.developerToken = developerToken;
            o.userAgent = userAgent;
            return o;
        }
    }
}
