// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.footholdtech.fivetran.outputs.ConnectorSchemaConfigSchemaTable;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConnectorSchemaConfigSchema {
    /**
     * @return The boolean value specifying whether the sync for the schema into the destination is enabled.
     * 
     */
    private @Nullable String enabled;
    /**
     * @return The schema name within your destination in accordance with Fivetran conventional rules.
     * 
     */
    private String name;
    private @Nullable List<ConnectorSchemaConfigSchemaTable> tables;

    private ConnectorSchemaConfigSchema() {}
    /**
     * @return The boolean value specifying whether the sync for the schema into the destination is enabled.
     * 
     */
    public Optional<String> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    /**
     * @return The schema name within your destination in accordance with Fivetran conventional rules.
     * 
     */
    public String name() {
        return this.name;
    }
    public List<ConnectorSchemaConfigSchemaTable> tables() {
        return this.tables == null ? List.of() : this.tables;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConnectorSchemaConfigSchema defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String enabled;
        private String name;
        private @Nullable List<ConnectorSchemaConfigSchemaTable> tables;
        public Builder() {}
        public Builder(ConnectorSchemaConfigSchema defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.name = defaults.name;
    	      this.tables = defaults.tables;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable String enabled) {
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder tables(@Nullable List<ConnectorSchemaConfigSchemaTable> tables) {
            this.tables = tables;
            return this;
        }
        public Builder tables(ConnectorSchemaConfigSchemaTable... tables) {
            return tables(List.of(tables));
        }
        public ConnectorSchemaConfigSchema build() {
            final var o = new ConnectorSchemaConfigSchema();
            o.enabled = enabled;
            o.name = name;
            o.tables = tables;
            return o;
        }
    }
}
