// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDbtProjectsProject {
    /**
     * @return The timestamp of when the project was created in your account.
     * 
     */
    private String createdAt;
    /**
     * @return The unique identifier for the User within the Fivetran system who created the DBT Project.
     * 
     */
    private String createdById;
    /**
     * @return The name of the group within your account related to the project.
     * 
     */
    private String groupId;
    /**
     * @return The unique identifier for the dbt project within the Fivetran system.
     * 
     */
    private String id;

    private GetDbtProjectsProject() {}
    /**
     * @return The timestamp of when the project was created in your account.
     * 
     */
    public String createdAt() {
        return this.createdAt;
    }
    /**
     * @return The unique identifier for the User within the Fivetran system who created the DBT Project.
     * 
     */
    public String createdById() {
        return this.createdById;
    }
    /**
     * @return The name of the group within your account related to the project.
     * 
     */
    public String groupId() {
        return this.groupId;
    }
    /**
     * @return The unique identifier for the dbt project within the Fivetran system.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDbtProjectsProject defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createdAt;
        private String createdById;
        private String groupId;
        private String id;
        public Builder() {}
        public Builder(GetDbtProjectsProject defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createdAt = defaults.createdAt;
    	      this.createdById = defaults.createdById;
    	      this.groupId = defaults.groupId;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt);
            return this;
        }
        @CustomType.Setter
        public Builder createdById(String createdById) {
            this.createdById = Objects.requireNonNull(createdById);
            return this;
        }
        @CustomType.Setter
        public Builder groupId(String groupId) {
            this.groupId = Objects.requireNonNull(groupId);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public GetDbtProjectsProject build() {
            final var o = new GetDbtProjectsProject();
            o.createdAt = createdAt;
            o.createdById = createdById;
            o.groupId = groupId;
            o.id = id;
            return o;
        }
    }
}
