// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.footholdtech.fivetran.outputs.GetMetadataSchemasMetadataSchema;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetMetadataSchemasResult {
    /**
     * @return The unique identifier for the connector within the Fivetran system. Data-source will represent a set of schemas of connector.
     * 
     */
    private String id;
    private List<GetMetadataSchemasMetadataSchema> metadataSchemas;

    private GetMetadataSchemasResult() {}
    /**
     * @return The unique identifier for the connector within the Fivetran system. Data-source will represent a set of schemas of connector.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetMetadataSchemasMetadataSchema> metadataSchemas() {
        return this.metadataSchemas;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMetadataSchemasResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<GetMetadataSchemasMetadataSchema> metadataSchemas;
        public Builder() {}
        public Builder(GetMetadataSchemasResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.metadataSchemas = defaults.metadataSchemas;
        }

        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder metadataSchemas(List<GetMetadataSchemasMetadataSchema> metadataSchemas) {
            this.metadataSchemas = Objects.requireNonNull(metadataSchemas);
            return this;
        }
        public Builder metadataSchemas(GetMetadataSchemasMetadataSchema... metadataSchemas) {
            return metadataSchemas(List.of(metadataSchemas));
        }
        public GetMetadataSchemasResult build() {
            final var o = new GetMetadataSchemasResult();
            o.id = id;
            o.metadataSchemas = metadataSchemas;
            return o;
        }
    }
}
