// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.footholdtech.fivetran.outputs.GetTeamUserMembershipsUser;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetTeamUserMembershipsResult {
    /**
     * @return The unique identifier for resource.
     * 
     */
    private String id;
    /**
     * @return The unique identifier for the team within your account.
     * 
     */
    private String teamId;
    private @Nullable List<GetTeamUserMembershipsUser> users;

    private GetTeamUserMembershipsResult() {}
    /**
     * @return The unique identifier for resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The unique identifier for the team within your account.
     * 
     */
    public String teamId() {
        return this.teamId;
    }
    public List<GetTeamUserMembershipsUser> users() {
        return this.users == null ? List.of() : this.users;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamUserMembershipsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String teamId;
        private @Nullable List<GetTeamUserMembershipsUser> users;
        public Builder() {}
        public Builder(GetTeamUserMembershipsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.teamId = defaults.teamId;
    	      this.users = defaults.users;
        }

        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder teamId(String teamId) {
            this.teamId = Objects.requireNonNull(teamId);
            return this;
        }
        @CustomType.Setter
        public Builder users(@Nullable List<GetTeamUserMembershipsUser> users) {
            this.users = users;
            return this;
        }
        public Builder users(GetTeamUserMembershipsUser... users) {
            return users(List.of(users));
        }
        public GetTeamUserMembershipsResult build() {
            final var o = new GetTeamUserMembershipsResult();
            o.id = id;
            o.teamId = teamId;
            o.users = users;
            return o;
        }
    }
}
