// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTeamsTeam {
    /**
     * @return The description of the team within your account.
     * 
     */
    private String description;
    /**
     * @return The unique identifier for the team within your account.
     * 
     */
    private String id;
    /**
     * @return The name of the team within your account.
     * 
     */
    private String name;
    /**
     * @return The account role of the team.
     * 
     */
    private String role;

    private GetTeamsTeam() {}
    /**
     * @return The description of the team within your account.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The unique identifier for the team within your account.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the team within your account.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The account role of the team.
     * 
     */
    public String role() {
        return this.role;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamsTeam defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String id;
        private String name;
        private String role;
        public Builder() {}
        public Builder(GetTeamsTeam defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.role = defaults.role;
        }

        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            this.role = Objects.requireNonNull(role);
            return this;
        }
        public GetTeamsTeam build() {
            final var o = new GetTeamsTeam();
            o.description = description;
            o.id = id;
            o.name = name;
            o.role = role;
            return o;
        }
    }
}
