// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.footholdtech.fivetran.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class TeamUserMembershipUser {
    /**
     * @return The team&#39;s role that links the team and the user
     * 
     */
    private String role;
    /**
     * @return The user unique identifier
     * 
     */
    private String userId;

    private TeamUserMembershipUser() {}
    /**
     * @return The team&#39;s role that links the team and the user
     * 
     */
    public String role() {
        return this.role;
    }
    /**
     * @return The user unique identifier
     * 
     */
    public String userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TeamUserMembershipUser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String role;
        private String userId;
        public Builder() {}
        public Builder(TeamUserMembershipUser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.role = defaults.role;
    	      this.userId = defaults.userId;
        }

        @CustomType.Setter
        public Builder role(String role) {
            this.role = Objects.requireNonNull(role);
            return this;
        }
        @CustomType.Setter
        public Builder userId(String userId) {
            this.userId = Objects.requireNonNull(userId);
            return this;
        }
        public TeamUserMembershipUser build() {
            final var o = new TeamUserMembershipUser();
            o.role = role;
            o.userId = userId;
            return o;
        }
    }
}
