// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class ConnectorConfigReportConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: Set the value to `PREBUILT` if it's one of the preconfigured reports (see the `prebuilt_report_type` option). Otherwise, set to `CUSTOM`.
        /// </summary>
        [Input("configType")]
        public Input<string>? ConfigType { get; set; }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: [Currency](https://developer.yahooinc.com/dsp/api/docs/reporting/payloadspec.html) used in a report. Default value: `USD`.
        /// </summary>
        [Input("currency")]
        public Input<string>? Currency { get; set; }

        [Input("dimensions")]
        private InputList<string>? _dimensions;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: [Dimensions](https://developer.yahooinc.com/dsp/api/docs/reporting/dimensions.html) used in a report. Must be populated if `config_type` is set to `CUSTOM`.
        /// </summary>
        public InputList<string> Dimensions
        {
            get => _dimensions ?? (_dimensions = new InputList<string>());
            set => _dimensions = value;
        }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: The [granularity](https://developer.yahooinc.com/dsp/api/docs/reporting/range-examples.html#interval-type-id) of data in a report. Default value: `DAY`.
        /// </summary>
        [Input("intervalType")]
        public Input<string>? IntervalType { get; set; }

        [Input("metrics")]
        private InputList<string>? _metrics;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: [Metrics](https://developer.yahooinc.com/dsp/api/docs/reporting/metrics.html) used in a report. Must be populated if `config_type` is set to `CUSTOM`.
        /// </summary>
        public InputList<string> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<string>());
            set => _metrics = value;
        }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: Specific report type to sync. Must be populated if `config_type` is set to `PREBUILT`.
        /// </summary>
        [Input("prebuiltReportType")]
        public Input<string>? PrebuiltReportType { get; set; }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: Table name in destination.
        /// </summary>
        [Input("reportName")]
        public Input<string>? ReportName { get; set; }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: Specify the time zone to be used to request report data
        /// </summary>
        [Input("timeZone")]
        public Input<string>? TimeZone { get; set; }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `yahoo_dsp`: Use advertiser timezone to request report data.
        /// </summary>
        [Input("useAdvertiserTimezone")]
        public Input<bool>? UseAdvertiserTimezone { get; set; }

        public ConnectorConfigReportConfigGetArgs()
        {
        }
        public static new ConnectorConfigReportConfigGetArgs Empty => new ConnectorConfigReportConfigGetArgs();
    }
}
