// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class ConnectorConfigReportFilterArgs : global::Pulumi.ResourceArgs
    {
        [Input("dimension")]
        public Input<string>? Dimension { get; set; }

        [Input("expression")]
        public Input<string>? Expression { get; set; }

        [Input("filterType")]
        public Input<string>? FilterType { get; set; }

        [Input("matchType")]
        public Input<string>? MatchType { get; set; }

        public ConnectorConfigReportFilterArgs()
        {
        }
        public static new ConnectorConfigReportFilterArgs Empty => new ConnectorConfigReportFilterArgs();
    }
}
