// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class ConnectorConfigAccountsRedditAdArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `reddit_ads`: Reddit username of the additional linked account.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ConnectorConfigAccountsRedditAdArgs()
        {
        }
        public static new ConnectorConfigAccountsRedditAdArgs Empty => new ConnectorConfigAccountsRedditAdArgs();
    }
}
