// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class ConnectorSchemaConfigSchemasTablesColumnsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The boolean value specifying whether the sync for the schema into the destination is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The boolean value specifying whether a column should be hashed.
        /// </summary>
        [Input("hashed")]
        public Input<bool>? Hashed { get; set; }

        public ConnectorSchemaConfigSchemasTablesColumnsGetArgs()
        {
        }
        public static new ConnectorSchemaConfigSchemasTablesColumnsGetArgs Empty => new ConnectorSchemaConfigSchemasTablesColumnsGetArgs();
    }
}
