// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class ConnectorConfigAdobeAnalyticsConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("calculatedMetrics")]
        private InputList<string>? _calculatedMetrics;
        public InputList<string> CalculatedMetrics
        {
            get => _calculatedMetrics ?? (_calculatedMetrics = new InputList<string>());
            set => _calculatedMetrics = value;
        }

        [Input("elements")]
        private InputList<string>? _elements;
        public InputList<string> Elements
        {
            get => _elements ?? (_elements = new InputList<string>());
            set => _elements = value;
        }

        [Input("metrics")]
        private InputList<string>? _metrics;
        public InputList<string> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<string>());
            set => _metrics = value;
        }

        [Input("reportSuites")]
        private InputList<string>? _reportSuites;
        public InputList<string> ReportSuites
        {
            get => _reportSuites ?? (_reportSuites = new InputList<string>());
            set => _reportSuites = value;
        }

        [Input("segments")]
        private InputList<string>? _segments;
        public InputList<string> Segments
        {
            get => _segments ?? (_segments = new InputList<string>());
            set => _segments = value;
        }

        [Input("syncMode")]
        public Input<string>? SyncMode { get; set; }

        [Input("table")]
        public Input<string>? Table { get; set; }

        public ConnectorConfigAdobeAnalyticsConfigurationArgs()
        {
        }
        public static new ConnectorConfigAdobeAnalyticsConfigurationArgs Empty => new ConnectorConfigAdobeAnalyticsConfigurationArgs();
    }
}
