// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class GetConnectorConfigCustomTableArgs : global::Pulumi.InvokeArgs
    {
        [Input("actionBreakdowns", required: true)]
        private List<string>? _actionBreakdowns;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: List of action_breakdowns which connector will sync. [Possible action_breakdowns values](https://fivetran.com/docs/connectors/applications/facebook-ads#actionbreakdowns).
        /// </summary>
        public List<string> ActionBreakdowns
        {
            get => _actionBreakdowns ?? (_actionBreakdowns = new List<string>());
            set => _actionBreakdowns = value;
        }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: The report time of action stats. [Possible action_report time values](https://fivetran.com/docs/connectors/applications/facebook-ads#actionreporttime).
        /// </summary>
        [Input("actionReportTime", required: true)]
        public string ActionReportTime { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: Options to select aggregation duration. [Possible aggregation values](https://fivetran.com/docs/connectors/applications/facebook-ads#aggregation).
        /// </summary>
        [Input("aggregation", required: true)]
        public string Aggregation { get; set; } = null!;

        [Input("breakdowns", required: true)]
        private List<string>? _breakdowns;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: List of breakdowns which connector will sync. [Possible breakdowns values](https://fivetran.com/docs/connectors/applications/facebook-ads#breakdowns).
        /// </summary>
        public List<string> Breakdowns
        {
            get => _breakdowns ?? (_breakdowns = new List<string>());
            set => _breakdowns = value;
        }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: Time period to attribute conversions based on clicks. [Possible click_attribution_window values](https://fivetran.com/docs/connectors/applications/facebook-ads#clickattributionwindow).
        /// </summary>
        [Input("clickAttributionWindow", required: true)]
        public string ClickAttributionWindow { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: Option to select Prebuilt Reports or Custom Reports. [Possible config_type values](https://fivetran.com/docs/connectors/applications/facebook-ads#configtype).
        /// </summary>
        [Input("configType", required: true)]
        public string ConfigType { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: Time period to attribute conversions based on engaged views. [Possible view_attribution_window values](https://fivetran.com/docs/connectors/applications/facebook-ads#engagedviewattributionwindow).
        /// </summary>
        [Input("engagedViewAttributionWindow", required: true)]
        public string EngagedViewAttributionWindow { get; set; } = null!;

        [Input("fields", required: true)]
        private List<string>? _fields;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: List of fields which connector will sync. [Possible field values](https://fivetran.com/docs/connectors/applications/facebook-ads#fields).
        /// </summary>
        public List<string> Fields
        {
            get => _fields ?? (_fields = new List<string>());
            set => _fields = value;
        }

        [Input("level", required: true)]
        public string Level { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: The report name to which connector will sync the data. [Possible prebuilt_report values](https://fivetran.com/docs/connectors/applications/facebook-ads#prebuiltreport).
        /// </summary>
        [Input("prebuiltReportName", required: true)]
        public string PrebuiltReportName { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: The table name within the schema to which the connector will sync the data. It must be unique within the connector and must comply with [Fivetran's naming conventions](https://fivetran.com/docs/getting-started/core-concepts#namingconventions).
        /// </summary>
        [Input("tableName", required: true)]
        public string TableName { get; set; } = null!;

        [Input("useUnifiedAttributionSetting", required: true)]
        public bool UseUnifiedAttributionSetting { get; set; }

        /// <summary>
        /// Field usage depends on `service` value: 
        /// 	- Service `facebook_ads`: Time period to attribute conversions based on views. [Possible view_attribution_window values](https://fivetran.com/docs/connectors/applications/facebook-ads#viewattributionwindow).
        /// </summary>
        [Input("viewAttributionWindow", required: true)]
        public string ViewAttributionWindow { get; set; } = null!;

        public GetConnectorConfigCustomTableArgs()
        {
        }
        public static new GetConnectorConfigCustomTableArgs Empty => new GetConnectorConfigCustomTableArgs();
    }
}
