// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class GetConnectorConfigAdobeAnalyticsConfigurationArgs : global::Pulumi.InvokeArgs
    {
        [Input("calculatedMetrics", required: true)]
        private List<string>? _calculatedMetrics;
        public List<string> CalculatedMetrics
        {
            get => _calculatedMetrics ?? (_calculatedMetrics = new List<string>());
            set => _calculatedMetrics = value;
        }

        [Input("elements", required: true)]
        private List<string>? _elements;
        public List<string> Elements
        {
            get => _elements ?? (_elements = new List<string>());
            set => _elements = value;
        }

        [Input("metrics", required: true)]
        private List<string>? _metrics;
        public List<string> Metrics
        {
            get => _metrics ?? (_metrics = new List<string>());
            set => _metrics = value;
        }

        [Input("reportSuites", required: true)]
        private List<string>? _reportSuites;
        public List<string> ReportSuites
        {
            get => _reportSuites ?? (_reportSuites = new List<string>());
            set => _reportSuites = value;
        }

        [Input("segments", required: true)]
        private List<string>? _segments;
        public List<string> Segments
        {
            get => _segments ?? (_segments = new List<string>());
            set => _segments = value;
        }

        [Input("syncMode", required: true)]
        public string SyncMode { get; set; } = null!;

        [Input("table", required: true)]
        public string Table { get; set; } = null!;

        public GetConnectorConfigAdobeAnalyticsConfigurationArgs()
        {
        }
        public static new GetConnectorConfigAdobeAnalyticsConfigurationArgs Empty => new GetConnectorConfigAdobeAnalyticsConfigurationArgs();
    }
}
