// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class GetConnectorConfigReportInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("aggregation", required: true)]
        public Input<string> Aggregation { get; set; } = null!;

        [Input("attributes", required: true)]
        private InputList<string>? _attributes;
        public InputList<string> Attributes
        {
            get => _attributes ?? (_attributes = new InputList<string>());
            set => _attributes = value;
        }

        [Input("configType", required: true)]
        public Input<string> ConfigType { get; set; } = null!;

        [Input("dimensions", required: true)]
        private InputList<string>? _dimensions;
        public InputList<string> Dimensions
        {
            get => _dimensions ?? (_dimensions = new InputList<string>());
            set => _dimensions = value;
        }

        [Input("fields", required: true)]
        private InputList<string>? _fields;
        public InputList<string> Fields
        {
            get => _fields ?? (_fields = new InputList<string>());
            set => _fields = value;
        }

        [Input("filter", required: true)]
        public Input<string> Filter { get; set; } = null!;

        [Input("filterFieldName", required: true)]
        public Input<string> FilterFieldName { get; set; } = null!;

        [Input("filterType", required: true)]
        public Input<string> FilterType { get; set; } = null!;

        [Input("filterValue", required: true)]
        public Input<string> FilterValue { get; set; } = null!;

        [Input("metrics", required: true)]
        private InputList<string>? _metrics;
        public InputList<string> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<string>());
            set => _metrics = value;
        }

        [Input("prebuiltReport", required: true)]
        public Input<string> PrebuiltReport { get; set; } = null!;

        [Input("reportType", required: true)]
        public Input<string> ReportType { get; set; } = null!;

        [Input("rollbackWindow", required: true)]
        public Input<string> RollbackWindow { get; set; } = null!;

        [Input("searchTypes", required: true)]
        private InputList<string>? _searchTypes;
        public InputList<string> SearchTypes
        {
            get => _searchTypes ?? (_searchTypes = new InputList<string>());
            set => _searchTypes = value;
        }

        [Input("segmentIds", required: true)]
        private InputList<string>? _segmentIds;
        public InputList<string> SegmentIds
        {
            get => _segmentIds ?? (_segmentIds = new InputList<string>());
            set => _segmentIds = value;
        }

        [Input("segments", required: true)]
        private InputList<string>? _segments;
        public InputList<string> Segments
        {
            get => _segments ?? (_segments = new InputList<string>());
            set => _segments = value;
        }

        [Input("table", required: true)]
        public Input<string> Table { get; set; } = null!;

        public GetConnectorConfigReportInputArgs()
        {
        }
        public static new GetConnectorConfigReportInputArgs Empty => new GetConnectorConfigReportInputArgs();
    }
}
