// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class GetConnectionStatusTaskArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Task code.
        /// </summary>
        [Input("code", required: true)]
        public string Code { get; set; } = null!;

        /// <summary>
        /// Task message.
        /// </summary>
        [Input("message", required: true)]
        public string Message { get; set; } = null!;

        public GetConnectionStatusTaskArgs()
        {
        }
        public static new GetConnectionStatusTaskArgs Empty => new GetConnectionStatusTaskArgs();
    }
}
