// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class GetDestinationConfigArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The connector authorization settings. Check possible config formats in [create method](https://www.terraform.io/openapi/reference/v1/operation/create_connector/)
        /// </summary>
        [Input("auth")]
        public string? Auth { get; set; }

        /// <summary>
        /// Authentication type. Default value: `PASSWORD`.
        /// </summary>
        [Input("authType")]
        public string? AuthType { get; set; }

        /// <summary>
        /// Customer bucket. If specified, your GCS bucket will be used to process the data instead of a Fivetran-managed bucket. The bucket must be present in the same location as the dataset location.
        /// </summary>
        [Input("bucket")]
        public string? Bucket { get; set; }

        /// <summary>
        /// Catalog name
        /// </summary>
        [Input("catalog")]
        public string? Catalog { get; set; }

        /// <summary>
        /// ClientId of your Azure Data Lake Storage
        /// </summary>
        [Input("clientId")]
        public string? ClientId { get; set; }

        /// <summary>
        /// Cluster ID. Must be populated if `connection_type` is set to `SshTunnel` and `auth_type` is set to `IAM`.
        /// </summary>
        [Input("clusterId")]
        public string? ClusterId { get; set; }

        /// <summary>
        /// Cluster region. Must be populated if `connection_type` is set to `SshTunnel` and `auth_type` is set to `IAM`.
        /// </summary>
        [Input("clusterRegion")]
        public string? ClusterRegion { get; set; }

        /// <summary>
        /// Connection method. Default value: `Directly`.
        /// </summary>
        [Input("connectionType")]
        public string? ConnectionType { get; set; }

        /// <summary>
        /// Container Name of your Azure Data Lake Storage
        /// </summary>
        [Input("containerName")]
        public string? ContainerName { get; set; }

        /// <summary>
        /// Whether to create external tables
        /// </summary>
        [Input("createExternalTables")]
        public string? CreateExternalTables { get; set; }

        /// <summary>
        /// Data location. Datasets will reside in this location.
        /// </summary>
        [Input("dataSetLocation")]
        public string? DataSetLocation { get; set; }

        /// <summary>
        /// Database name
        /// </summary>
        [Input("database")]
        public string? Database { get; set; }

        /// <summary>
        /// External location to store Delta tables. Default value: `""`  (null). By default, the external tables will reside in the `/{schema}/{table}` path, and if you specify an external location in the `{externalLocation}/{schema}/{table}` path.
        /// </summary>
        [Input("externalLocation")]
        public string? ExternalLocation { get; set; }

        /// <summary>
        /// ARN of the role which you created with different required policy mentioned in our setup guide
        /// </summary>
        [Input("fivetranRoleArn")]
        public string? FivetranRoleArn { get; set; }

        /// <summary>
        /// Server name
        /// </summary>
        [Input("host")]
        public string? Host { get; set; }

        /// <summary>
        /// HTTP path
        /// </summary>
        [Input("httpPath")]
        public string? HttpPath { get; set; }

        /// <summary>
        /// Indicates that a private key is encrypted. The default value: `false`. The field can be specified if authentication type is `KEY_PAIR`.
        /// </summary>
        [Input("isPrivateKeyEncrypted", required: true)]
        public string IsPrivateKeyEncrypted { get; set; } = null!;

        [Input("lakehouseName")]
        private string? _lakehouseName;

        /// <summary>
        /// OneLake lakehouse name
        /// </summary>
        public string? LakehouseName
        {
            get => _lakehouseName;
            set => _lakehouseName = value;
        }

        [Input("passphrase")]
        private string? _passphrase;

        /// <summary>
        /// In case private key is encrypted, you are required to enter passphrase that was used to encrypt the private key. The field can be specified if authentication type is `KEY_PAIR`.
        /// </summary>
        public string? Passphrase
        {
            get => _passphrase;
            set => _passphrase = value;
        }

        [Input("password")]
        private string? _password;

        /// <summary>
        /// Database user password
        /// </summary>
        public string? Password
        {
            get => _password;
            set => _password = value;
        }

        [Input("personalAccessToken")]
        private string? _personalAccessToken;

        /// <summary>
        /// Personal access token
        /// </summary>
        public string? PersonalAccessToken
        {
            get => _personalAccessToken;
            set => _personalAccessToken = value;
        }

        /// <summary>
        /// Server port number
        /// </summary>
        [Input("port")]
        public int? Port { get; set; }

        /// <summary>
        /// Prefix path of the bucket for which you have configured access policy. It is not required if access has been granted to entire Bucket in the access policy
        /// </summary>
        [Input("prefixPath")]
        public string? PrefixPath { get; set; }

        [Input("privateKey")]
        private string? _privateKey;

        /// <summary>
        /// Private access key.  The field should be specified if authentication type is `KEY_PAIR`.
        /// </summary>
        public string? PrivateKey
        {
            get => _privateKey;
            set => _privateKey = value;
        }

        /// <summary>
        /// BigQuery project ID
        /// </summary>
        [Input("projectId")]
        public string? ProjectId { get; set; }

        /// <summary>
        /// Public key to grant Fivetran SSH access to git repository.
        /// </summary>
        [Input("publicKey", required: true)]
        public string PublicKey { get; set; } = null!;

        /// <summary>
        /// Region of your AWS S3 bucket
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        /// <summary>
        /// The group role that you would like to assign this new user to. Supported group roles: ‘Destination Administrator‘, ‘Destination Reviewer‘, ‘Destination Analyst‘, ‘Connector Creator‘, or a custom destination role
        /// </summary>
        [Input("role")]
        public string? Role { get; set; }

        [Input("roleArn")]
        private string? _roleArn;

        /// <summary>
        /// Role ARN with Redshift permissions. Required if authentication type is `IAM`.
        /// </summary>
        public string? RoleArn
        {
            get => _roleArn;
            set => _roleArn = value;
        }

        [Input("secretKey")]
        private string? _secretKey;

        /// <summary>
        /// Private key of the customer service account. If specified, your service account will be used to process the data instead of the Fivetran-managed service account.
        /// </summary>
        public string? SecretKey
        {
            get => _secretKey;
            set => _secretKey = value;
        }

        [Input("secretValue")]
        private string? _secretValue;

        /// <summary>
        /// Secret Value of your Azure Data Lake Storage
        /// </summary>
        public string? SecretValue
        {
            get => _secretValue;
            set => _secretValue = value;
        }

        /// <summary>
        /// Server name
        /// </summary>
        [Input("serverHostName")]
        public string? ServerHostName { get; set; }

        /// <summary>
        /// Storage Account Name of your Azure Data Lake Storage
        /// </summary>
        [Input("storageAccountName")]
        public string? StorageAccountName { get; set; }

        /// <summary>
        /// TenantId of your Azure Data Lake Storage
        /// </summary>
        [Input("tenantId")]
        public string? TenantId { get; set; }

        /// <summary>
        /// SSH server name. Must be populated if `connection_type` is set to `SshTunnel`.
        /// </summary>
        [Input("tunnelHost")]
        public string? TunnelHost { get; set; }

        /// <summary>
        /// SSH server port name. Must be populated if `connection_type` is set to `SshTunnel`.
        /// </summary>
        [Input("tunnelPort")]
        public string? TunnelPort { get; set; }

        /// <summary>
        /// SSH user name. Must be populated if `connection_type` is set to `SshTunnel`.
        /// </summary>
        [Input("tunnelUser")]
        public string? TunnelUser { get; set; }

        /// <summary>
        /// Database user name
        /// </summary>
        [Input("user")]
        public string? User { get; set; }

        [Input("workspaceName")]
        private string? _workspaceName;

        /// <summary>
        /// OneLake workspace name
        /// </summary>
        public string? WorkspaceName
        {
            get => _workspaceName;
            set => _workspaceName = value;
        }

        public GetDestinationConfigArgs()
        {
        }
        public static new GetDestinationConfigArgs Empty => new GetDestinationConfigArgs();
    }
}
