// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class GetGroupConnectorsConnectorStatusArgs : global::Pulumi.InvokeArgs
    {
        [Input("isHistoricalSync", required: true)]
        public bool IsHistoricalSync { get; set; }

        [Input("setupState", required: true)]
        public string SetupState { get; set; } = null!;

        [Input("syncState", required: true)]
        public string SyncState { get; set; } = null!;

        [Input("tasks", required: true)]
        private List<Inputs.GetGroupConnectorsConnectorStatusTaskArgs>? _tasks;
        public List<Inputs.GetGroupConnectorsConnectorStatusTaskArgs> Tasks
        {
            get => _tasks ?? (_tasks = new List<Inputs.GetGroupConnectorsConnectorStatusTaskArgs>());
            set => _tasks = value;
        }

        [Input("updateState", required: true)]
        public string UpdateState { get; set; } = null!;

        [Input("warnings", required: true)]
        private List<Inputs.GetGroupConnectorsConnectorStatusWarningArgs>? _warnings;
        public List<Inputs.GetGroupConnectorsConnectorStatusWarningArgs> Warnings
        {
            get => _warnings ?? (_warnings = new List<Inputs.GetGroupConnectorsConnectorStatusWarningArgs>());
            set => _warnings = value;
        }

        public GetGroupConnectorsConnectorStatusArgs()
        {
        }
        public static new GetGroupConnectorsConnectorStatusArgs Empty => new GetGroupConnectorsConnectorStatusArgs();
    }
}
