// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Footholdtech.Fivetran.Inputs
{

    public sealed class TransformationScheduleArgs : global::Pulumi.ResourceArgs
    {
        [Input("connectionIds")]
        private InputList<string>? _connectionIds;

        /// <summary>
        /// The list of the connection identifiers to be used for the integrated schedule. Not expected for QUICKSTART transformations
        /// </summary>
        public InputList<string> ConnectionIds
        {
            get => _connectionIds ?? (_connectionIds = new InputList<string>());
            set => _connectionIds = value;
        }

        [Input("crons")]
        private InputList<string>? _crons;

        /// <summary>
        /// Cron schedule: list of CRON strings. Used for for CRON schedule type
        /// </summary>
        public InputList<string> Crons
        {
            get => _crons ?? (_crons = new InputList<string>());
            set => _crons = value;
        }

        [Input("daysOfWeeks")]
        private InputList<string>? _daysOfWeeks;

        /// <summary>
        /// The set of the days of the week the transformation should be launched on. The following values are supported: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY. Used for for INTEGRATED schedule type
        /// </summary>
        public InputList<string> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<string>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// The time interval in minutes between subsequent transformation runs. Used for for INTERVAL schedule type
        /// </summary>
        [Input("interval")]
        public Input<int>? Interval { get; set; }

        /// <summary>
        /// The type of the schedule to run the Transformation on. The following values are supported: INTEGRATED, TIME*OF*DAY, INTERVAL, CRON.
        /// </summary>
        [Input("scheduleType")]
        public Input<string>? ScheduleType { get; set; }

        /// <summary>
        /// The boolean flag that enables the Smart Syncing schedule
        /// </summary>
        [Input("smartSyncing")]
        public Input<bool>? SmartSyncing { get; set; }

        /// <summary>
        /// The time of the day the transformation should be launched at. Supported values are: "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00". Used for for TIME*OF*DAY schedule type
        /// </summary>
        [Input("timeOfDay")]
        public Input<string>? TimeOfDay { get; set; }

        public TransformationScheduleArgs()
        {
        }
        public static new TransformationScheduleArgs Empty => new TransformationScheduleArgs();
    }
}
