// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This data source returns a list of all dbt Projects within your Fivetran account.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fivetran from "@pulumi/fivetran";
 *
 * const myProjects = fivetran.getDbtProjects({});
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getDbtProjects(args?: GetDbtProjectsArgs, opts?: pulumi.InvokeOptions): Promise<GetDbtProjectsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fivetran:index/getDbtProjects:getDbtProjects", {
        "projects": args.projects,
    }, opts);
}

/**
 * A collection of arguments for invoking getDbtProjects.
 */
export interface GetDbtProjectsArgs {
    projects?: inputs.GetDbtProjectsProject[];
}

/**
 * A collection of values returned by getDbtProjects.
 */
export interface GetDbtProjectsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly projects: outputs.GetDbtProjectsProject[];
}
/**
 * This data source returns a list of all dbt Projects within your Fivetran account.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fivetran from "@pulumi/fivetran";
 *
 * const myProjects = fivetran.getDbtProjects({});
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getDbtProjectsOutput(args?: GetDbtProjectsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDbtProjectsResult> {
    return pulumi.output(args).apply((a: any) => getDbtProjects(a, opts))
}

/**
 * A collection of arguments for invoking getDbtProjects.
 */
export interface GetDbtProjectsOutputArgs {
    projects?: pulumi.Input<pulumi.Input<inputs.GetDbtProjectsProjectArgs>[]>;
}
